# Artificial Neural Network - from scratch

- making a ANN from scratch without importing any tensorflow libraries


In [9]:
import numpy as np
import pandas as pd

## 1. Independent variable Defining - INPUT Feature set:

In [10]:
#Independent variables
input_set = np.array([[0,1,0], 
                      [0,0,1], 
                      [1,0,0], 
                      [1,1,0], 
                      [1,1,1], 
                      [0,1,1],
                      [0,1,0]])
input_set

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [0, 1, 0]])

## 2. Dependent Variable Defining - Labels:


In [11]:
labels = np.array([[1,
                   0,
                   0,
                   1,
                   1,
                   0,
                   1,
                   ]])
labels

array([[1, 0, 0, 1, 1, 0, 1]])

In [12]:
#converting lables into vectors:
labels = labels.reshape(7,1)
labels

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1]])

## 3. Hyperparameters [learning rate - alpha] Defining:

In [13]:
#learning rate
lr = 0.05

## 4. Initializing Weights (w) and Bias (b):

- .seed() - for fetching same values on execution of the code below,


In [14]:
len(input_set[0])

3

In [15]:
np.random.seed(50)

# size of weights will be same as that of input values here 3
weights = np.random.rand(3,1)

# Size of bias in constant
bias = np.random.rand(1)

print("\nWeights: ",weights)
print("\nbias: ", bias)
print("\nForward Propagation equation: z = x*w + b",)


Weights:  [[0.49460165]
 [0.2280831 ]
 [0.25547392]]

bias:  [0.39632991]

Forward Propagation equation: z = x*w + b


## 5. Activation function Defining:

In [16]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

sigmoid(0)

0.5

## 6. Activation function Derivative:

- Here, for Sigmoid: d(sigmoid)/dx = sigmoid(x)*(1-sigmoid(x))

In [17]:
def derivative_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

---
## 7. BUILDING & TRAINING ANN MODEL:

In [20]:
np.dot(input_set, weights) + bias

array([[0.62441301],
       [0.65180383],
       [0.89093156],
       [1.11901466],
       [1.37448858],
       [0.87988694],
       [0.62441301]])

In [18]:
epochs = 30000

**Step:1: Forward Propagation Function: inputs.weights + bias (. for dot product)**


**Step:2: Feeding Forward Function to Activation function (here, sigmoid)**

**Step:3: BackPropagation:**
- **Calculating loss (error) using loss function** (i.e. difference b/w predicted value and original values.
- **Calculating Gradient (rate_of_change)** 
- **Transposing input_sets / weights as:** `Z = W'X + b`

**Step:4: Optimization:**
- **Commonly use Optimizer in ANN: Gradient Descent: <br> `w = w - lr*z` <br> `b = b - lr*z`**

In [78]:
# Building model:

def ANN_model(X_train, Y_train, weights, bias, epochs, learning_rate):
    lr = learning_rate
    labels = Y_train
    weights = weights
    bias = bias
    for epoch in range(epochs):
        inputs = X_train
        
        # Summation: X*W + b
        XW = np.dot(inputs, weights) + bias 
        
        # Activation: sigmoid
        z = sigmoid(XW)
        
        # Backpropogation:
        # Loss Function:
        error = z - labels
        print("\nEpoch: {}/{} :-------> Loss (ave.) : {}".format(epoch,epochs,error.mean()))
        
        # Rate of Change Calculation:
        deri_cost = error
        deri_pred = derivative_sigmoid(z)
        del_z = deri_cost*deri_pred
        
        # Transposing (any one of weights/inputs):
        inputs = inputs.T
        
        # Optimization:
        weights = weights - lr*np.dot(inputs, del_z)
        for i in del_z:
            bias = bias - lr*i  
        
        
    # return sigmoid(np.dot(single_test, weights) + bias)
    return (weights,bias)

In [81]:
# Training model:
model = ANN_model(input_set, labels, weights, bias, epochs, learning_rate=lr)


Epoch: 0/30000 :-------> Loss (ave.) : 0.13252162777741014

Epoch: 1/30000 :-------> Loss (ave.) : 0.1297430791874649

Epoch: 2/30000 :-------> Loss (ave.) : 0.12701972938980183

Epoch: 3/30000 :-------> Loss (ave.) : 0.12435167046154486

Epoch: 4/30000 :-------> Loss (ave.) : 0.12173890615982445

Epoch: 5/30000 :-------> Loss (ave.) : 0.11918135630964703

Epoch: 6/30000 :-------> Loss (ave.) : 0.11667886127121696

Epoch: 7/30000 :-------> Loss (ave.) : 0.11423118645490087

Epoch: 8/30000 :-------> Loss (ave.) : 0.1118380268542879

Epoch: 9/30000 :-------> Loss (ave.) : 0.10949901157015693

Epoch: 10/30000 :-------> Loss (ave.) : 0.10721370830056917

Epoch: 11/30000 :-------> Loss (ave.) : 0.10498162777472006

Epoch: 12/30000 :-------> Loss (ave.) : 0.10280222811058957

Epoch: 13/30000 :-------> Loss (ave.) : 0.10067491907877904

Epoch: 14/30000 :-------> Loss (ave.) : 0.09859906625720749

Epoch: 15/30000 :-------> Loss (ave.) : 0.09657399506353112

Epoch: 16/30000 :-------> Loss (ave


Epoch: 4066/30000 :-------> Loss (ave.) : 0.0005324537388143868

Epoch: 4067/30000 :-------> Loss (ave.) : 0.0005317688138421385

Epoch: 4068/30000 :-------> Loss (ave.) : 0.0005310843502758887

Epoch: 4069/30000 :-------> Loss (ave.) : 0.000530400347762236

Epoch: 4070/30000 :-------> Loss (ave.) : 0.000529716805947921

Epoch: 4071/30000 :-------> Loss (ave.) : 0.0005290337244802874

Epoch: 4072/30000 :-------> Loss (ave.) : 0.0005283511030069346

Epoch: 4073/30000 :-------> Loss (ave.) : 0.0005276689411755968

Epoch: 4074/30000 :-------> Loss (ave.) : 0.0005269872386345155

Epoch: 4075/30000 :-------> Loss (ave.) : 0.0005263059950321705

Epoch: 4076/30000 :-------> Loss (ave.) : 0.0005256252100173942

Epoch: 4077/30000 :-------> Loss (ave.) : 0.0005249448832393541

Epoch: 4078/30000 :-------> Loss (ave.) : 0.0005242650143471504

Epoch: 4079/30000 :-------> Loss (ave.) : 0.0005235856029908012

Epoch: 4080/30000 :-------> Loss (ave.) : 0.0005229066488203245

Epoch: 4081/30000 :-------


Epoch: 7300/30000 :-------> Loss (ave.) : -0.0004086373017309908

Epoch: 7301/30000 :-------> Loss (ave.) : -0.0004087307417519892

Epoch: 7302/30000 :-------> Loss (ave.) : -0.00040882412542776547

Epoch: 7303/30000 :-------> Loss (ave.) : -0.00040891745278995106

Epoch: 7304/30000 :-------> Loss (ave.) : -0.000409010723870334

Epoch: 7305/30000 :-------> Loss (ave.) : -0.000409103938700413

Epoch: 7306/30000 :-------> Loss (ave.) : -0.0004091970973117777

Epoch: 7307/30000 :-------> Loss (ave.) : -0.0004092901997359427

Epoch: 7308/30000 :-------> Loss (ave.) : -0.0004093832460047654

Epoch: 7309/30000 :-------> Loss (ave.) : -0.00040947623614944313

Epoch: 7310/30000 :-------> Loss (ave.) : -0.0004095691702015062

Epoch: 7311/30000 :-------> Loss (ave.) : -0.00040966204819268507

Epoch: 7312/30000 :-------> Loss (ave.) : -0.000409754870154199

Epoch: 7313/30000 :-------> Loss (ave.) : -0.00040984763611756625

Epoch: 7314/30000 :-------> Loss (ave.) : -0.0004099403461142697

Epoch: 


Epoch: 12894/30000 :-------> Loss (ave.) : -0.0005275048086200212

Epoch: 12895/30000 :-------> Loss (ave.) : -0.0005274965327155634

Epoch: 12896/30000 :-------> Loss (ave.) : -0.0005274882535019333

Epoch: 12897/30000 :-------> Loss (ave.) : -0.0005274799709808606

Epoch: 12898/30000 :-------> Loss (ave.) : -0.0005274716851540838

Epoch: 12899/30000 :-------> Loss (ave.) : -0.0005274633960232657

Epoch: 12900/30000 :-------> Loss (ave.) : -0.0005274551035902376

Epoch: 12901/30000 :-------> Loss (ave.) : -0.0005274468078565742

Epoch: 12902/30000 :-------> Loss (ave.) : -0.0005274385088240059

Epoch: 12903/30000 :-------> Loss (ave.) : -0.0005274302064940455

Epoch: 12904/30000 :-------> Loss (ave.) : -0.0005274219008685475

Epoch: 12905/30000 :-------> Loss (ave.) : -0.0005274135919493392

Epoch: 12906/30000 :-------> Loss (ave.) : -0.0005274052797378397

Epoch: 12907/30000 :-------> Loss (ave.) : -0.000527396964235879

Epoch: 12908/30000 :-------> Loss (ave.) : -0.0005273886454449


Epoch: 17550/30000 :-------> Loss (ave.) : -0.0004713849149879775

Epoch: 17551/30000 :-------> Loss (ave.) : -0.0004713715279061773

Epoch: 17552/30000 :-------> Loss (ave.) : -0.00047135814087714736

Epoch: 17553/30000 :-------> Loss (ave.) : -0.0004713447539011464

Epoch: 17554/30000 :-------> Loss (ave.) : -0.0004713313669785759

Epoch: 17555/30000 :-------> Loss (ave.) : -0.0004713179801093418

Epoch: 17556/30000 :-------> Loss (ave.) : -0.0004713045932939435

Epoch: 17557/30000 :-------> Loss (ave.) : -0.000471291206532514

Epoch: 17558/30000 :-------> Loss (ave.) : -0.00047127781982527227

Epoch: 17559/30000 :-------> Loss (ave.) : -0.00047126443317241855

Epoch: 17560/30000 :-------> Loss (ave.) : -0.0004712510465742295

Epoch: 17561/30000 :-------> Loss (ave.) : -0.00047123766003070105

Epoch: 17562/30000 :-------> Loss (ave.) : -0.00047122427354237155

Epoch: 17563/30000 :-------> Loss (ave.) : -0.00047121088710932416

Epoch: 17564/30000 :-------> Loss (ave.) : -0.0004711975


Epoch: 21246/30000 :-------> Loss (ave.) : -0.00042356206058634084

Epoch: 21247/30000 :-------> Loss (ave.) : -0.000423549800543362

Epoch: 21248/30000 :-------> Loss (ave.) : -0.000423537540943942

Epoch: 21249/30000 :-------> Loss (ave.) : -0.0004235252817883035

Epoch: 21250/30000 :-------> Loss (ave.) : -0.0004235130230762982

Epoch: 21251/30000 :-------> Loss (ave.) : -0.00042350076480812237

Epoch: 21252/30000 :-------> Loss (ave.) : -0.00042348850698369376

Epoch: 21253/30000 :-------> Loss (ave.) : -0.0004234762496030852

Epoch: 21254/30000 :-------> Loss (ave.) : -0.00042346399266632854

Epoch: 21255/30000 :-------> Loss (ave.) : -0.0004234517361733934

Epoch: 21256/30000 :-------> Loss (ave.) : -0.00042343948012433234

Epoch: 21257/30000 :-------> Loss (ave.) : -0.0004234272245193565

Epoch: 21258/30000 :-------> Loss (ave.) : -0.000423414969358289

Epoch: 21259/30000 :-------> Loss (ave.) : -0.00042340271464128297

Epoch: 21260/30000 :-------> Loss (ave.) : -0.000423390460


Epoch: 25527/30000 :-------> Loss (ave.) : -0.0003753333783449278

Epoch: 25528/30000 :-------> Loss (ave.) : -0.00037532311235386216

Epoch: 25529/30000 :-------> Loss (ave.) : -0.0003753128468190352

Epoch: 25530/30000 :-------> Loss (ave.) : -0.00037530258174032555

Epoch: 25531/30000 :-------> Loss (ave.) : -0.0003752923171176598

Epoch: 25532/30000 :-------> Loss (ave.) : -0.000375282052951149

Epoch: 25533/30000 :-------> Loss (ave.) : -0.0003752717892406693

Epoch: 25534/30000 :-------> Loss (ave.) : -0.0003752615259862855

Epoch: 25535/30000 :-------> Loss (ave.) : -0.0003752512631879814

Epoch: 25536/30000 :-------> Loss (ave.) : -0.0003752410008457068

Epoch: 25537/30000 :-------> Loss (ave.) : -0.0003752307389594504

Epoch: 25538/30000 :-------> Loss (ave.) : -0.00037522047752918883

Epoch: 25539/30000 :-------> Loss (ave.) : -0.00037521021655493057

Epoch: 25540/30000 :-------> Loss (ave.) : -0.00037519995603653634

Epoch: 25541/30000 :-------> Loss (ave.) : -0.00037518969


Epoch: 29860/30000 :-------> Loss (ave.) : -0.00033490709201719926

Epoch: 29861/30000 :-------> Loss (ave.) : -0.00033489864155515934

Epoch: 29862/30000 :-------> Loss (ave.) : -0.0003348901914713233

Epoch: 29863/30000 :-------> Loss (ave.) : -0.0003348817417655643

Epoch: 29864/30000 :-------> Loss (ave.) : -0.0003348732924380489

Epoch: 29865/30000 :-------> Loss (ave.) : -0.00033486484348850743

Epoch: 29866/30000 :-------> Loss (ave.) : -0.00033485639491718226

Epoch: 29867/30000 :-------> Loss (ave.) : -0.00033484794672385576

Epoch: 29868/30000 :-------> Loss (ave.) : -0.0003348394989085727

Epoch: 29869/30000 :-------> Loss (ave.) : -0.00033483105147123223

Epoch: 29870/30000 :-------> Loss (ave.) : -0.00033482260441198127

Epoch: 29871/30000 :-------> Loss (ave.) : -0.0003348141577306968

Epoch: 29872/30000 :-------> Loss (ave.) : -0.00033480571142742937

Epoch: 29873/30000 :-------> Loss (ave.) : -0.00033479726550205514

Epoch: 29874/30000 :-------> Loss (ave.) : -0.000334

In [82]:
model

(array([[ 6.94419646],
        [15.46542574],
        [-8.05810382]]),
 array([-10.89291326]))

In [94]:
# Prediction Function:
def ANN_model_predict(X_test_single, model):
    w,b = model
    return 1 if 0.5<(sigmoid(np.dot(X_test_single,w) + b)) else 0

## 8. Predicting:

In [95]:
X_test = np.array([[1,0,0],
                  [0,1,0]])

In [96]:
for single_test_data in X_test:
    print("\n ",ANN_model_predict(single_test_data, model))


  0

  1
